In [ ]:
# Numpy Notebook

## Contents
* creating a numpy array.
* creating a two-dimensional numpy array.
* reshaping the array.
* mathematical operations like addition, subraction, multiplication and division.
* transpose of a matrix
* array indexing
* slicing the array
* copying the array
* sorting the array
* locating the element in an array
* concatenating two arrays
* iterating through an array

In [1]:
import numpy as np

In [9]:
# creating a new numpy array
a = np.array([1,2,3,4,5,6,7,8,9])

# checking the type of a
print(type(a))

print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [4]:
# creating a two dimensional array
twod_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(twod_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# reshaping the array
a = a.reshape(3,3)

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# creating an another numpy array
b = np.array([[9,8,7],[6,5,4],[3,2,1]])

print(b)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [16]:
# adding two arrays
add = a+b

print(add)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [17]:
# subracting two arrays
sub = a-b

print(sub)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [18]:
# multiplying two array
mul = a*b

print(mul)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [19]:
# divide two arrays
div = a/b

print(div)

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [21]:
# transpose of a matrix
transpose_mat = np.transpose(a)

print(transpose_mat)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [22]:
# creating a one dimensional array
a = np.array([1,2,3,4,5,6,7,8,9])

In [24]:
# using index to access the elements of the array
# array indexing starts from 0 to length-1

print(a[0])
print(a[7])

1
8


In [26]:
# we can also use negative index to access elements from the back
# negative index starts from -1

print(a[-1])
print(a[-5])

9
5


In [30]:
# slicing the array
# slicing the array in numpy is similar to that of in python list

sliced_array = a[0:len(a)]

print(sliced_array)

[1 2 3 4 5 6 7 8 9]


In [33]:
sliced_array = a[0:4]
print(sliced_array)

# even though we mentioned 0:4 we only got elements from 0:3.
# the reason is that the array is sliced only to index before the ending number.
# i.e if it is 0:5 we will get elements from 0:4 and if its from 1:10 we will get 1:9

[1 2 3 4]


In [36]:
# creating a two dimensional array
l = [1,2,3]
two_d_list = []
for i in range(3):
    two_d_list.append(l)
    
a = np.array(two_d_list)
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [37]:
# slicing two dimensional array
# slice the array to get the first column of the matrix
sliced_array = a[0:3,0:1]

# 0:3 is used to slice the row.
# 0:1 is used to slice the column.

sliced_array

array([[1],
       [1],
       [1]])

In [39]:
# slice to get the first row of the matrix

sliced_array = a[0:1,:]

sliced_array

array([[1, 2, 3]])

In [45]:
# acess the element at the second row and third column
# since the array indexing starts from 0, 1 represent the second row and 2 represent the 3rd column
a[1][2]

3

In [66]:
# copying a numpy array
a = np.array(l)
print("initial array",a)

b = a
print("copied array",b)

b[0]=10
print("copied array after change", b)

print("intial array after changing copied array", a)

# the changes made in the array b is reflected in the array a too when using assignment operator.

initial array [1 2 3]
copied array [1 2 3]
copied array after change [10  2  3]
intial array after changing copied array [10  2  3]


In [65]:
# inorder to overcome this we can use several methods. Method 1 : using copy
a = np.array(l)
print("initial array",a)

b = np.copy(a)
print("copied array",b)

b[0]=10
print("copied array after change", b)

print("intial array after changing copied array", a)

# now the changes made in the array b isnt reflected on the array b.

initial array [1 2 3]
copied array [1 2 3]
copied array after change [10  2  3]
intial array after changing copied array [1 2 3]


In [78]:
# sorting an array
# using arange fn to create an array
a = np.arange(9,0,-1)
print("intial array",a)

# sorting the array in ascending order
a.sort()
print("array after sorted in asecnding order",a)

# sorting in desending order
a.sort(-1)
print("array after sorted in descending order",a)

intial array [9 8 7 6 5 4 3 2 1]
array after sorted in asecnding order [1 2 3 4 5 6 7 8 9]
array after sorted in descending order [1 2 3 4 5 6 7 8 9]


In [93]:
# finding an element in the array

a = np.array([1,2,3,2,5,1])

# finding the indices where element is 1
x = np.where(a==1)

# printing the indices in the array where the element is 1
for i in x:
    for j in i:
        print("element '1' is found at",j)
        
# finding the indices where element is 2
y = np.where(a==2)

for i in y:
    for j in i:
        print("element '2' is found at",j)

element '1' is found at 0
element '1' is found at 5
element '2' is found at 1
element '2' is found at 3


In [115]:
# joining two arrays
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[1,1],[1,1],[1,1]])

# joining the two arrays horizontally
c = np.concatenate((a,b), axis=1)
print("horizontally joining:","\n",c,"\n")

c = np.hstack((a,b))
print("horizontally joining:","\n",c,"\n")

# joining the two arrays vertically
d = np.concatenate((a,b), axis=0)
print("vertically joining:","\n",d,"\n")

d = np.vstack((a,b))
print("horizontally joining:","\n",d)

horizontally joining: 
 [[1 2 1 1]
 [3 4 1 1]
 [5 6 1 1]] 

horizontally joining: 
 [[1 2 1 1]
 [3 4 1 1]
 [5 6 1 1]] 

vertically joining: 
 [[1 2]
 [3 4]
 [5 6]
 [1 1]
 [1 1]
 [1 1]] 

horizontally joining: 
 [[1 2]
 [3 4]
 [5 6]
 [1 1]
 [1 1]
 [1 1]]


In [119]:
# iterating through an array
for row in a:
    for element in row:
        print(element)

1
2
3
4
5
6


In [123]:
# finding the shape of the array
rows, columns = a.shape
print(rows,columns)

# iterating through the arrray
for i in range(rows):
    for j in range(columns):
        print(a[i][j])

3 2
1
2
3
4
5
6


In [ ]:
# finding the inverse of a matrix using numpy
# first lets create a square matrix

a = np.array([12,23,22,15,16,19,92,93,22]).reshape(3,3)

inv_matrix = np.linalg.inv(a)
inv_matrix